# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\UserLog.ru\PycharmProjects\Simulation-modeling-of-queuing-systems-main\interface\ui\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(566, 465)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab1)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_tab = QtWidgets.QHBoxLayout()
        self.horizontalLayout_tab.setSpacing(0)
        self.horizontalLayout_tab.setObjectName("horizontalLayout_tab")
        self.horizontalLayout_main = QtWidgets.QHBoxLayout()
        self.horizontalLayout_main.setSpacing(0)
        self.horizontalLayout_main.setObjectName("horizontalLayout_main")
        self.verticalLayout_input_layout = QtWidgets.QVBoxLayout()
        self.verticalLayout_input_layout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_input_layout.setObjectName("verticalLayout_input_layout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_input_layout.addItem(spacerItem)
        self.layout_parameters_tab1 = QtWidgets.QVBoxLayout()
        self.layout_parameters_tab1.setSpacing(8)
        self.layout_parameters_tab1.setObjectName("layout_parameters_tab1")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.layout_parameters_tab1.addItem(spacerItem1)
        self.label_parameters = QtWidgets.QLabel(self.tab1)
        self.label_parameters.setObjectName("label_parameters")
        self.layout_parameters_tab1.addWidget(self.label_parameters)
        self.verticalLayout_input_layout.addLayout(self.layout_parameters_tab1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_input_layout.addItem(spacerItem2)
        self.launch_button_tab1 = QtWidgets.QPushButton(self.tab1)
        self.launch_button_tab1.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.launch_button_tab1.sizePolicy().hasHeightForWidth())
        self.launch_button_tab1.setSizePolicy(sizePolicy)
        self.launch_button_tab1.setMinimumSize(QtCore.QSize(0, 30))
        self.launch_button_tab1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.launch_button_tab1.setStyleSheet("#pushButton {\n"
"  border: 1px solid#adadad;\n"
"  background-color: rgb(225, 225, 225);\n"
"  color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"#pushButton:hover {\n"
"  border: 1px solid#0078d7;\n"
"  background-color: rgb(229, 241, 251);\n"
"  color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"#pushButton:pressed {  \n"
"  border: 1px solid#005499;\n"
"  background-color: rgb(204, 228, 247);\n"
"  color: rgb(0, 0, 0);\n"
"}")
        self.launch_button_tab1.setCheckable(False)
        self.launch_button_tab1.setChecked(False)
        self.launch_button_tab1.setAutoRepeat(False)
        self.launch_button_tab1.setAutoExclusive(False)
        self.launch_button_tab1.setAutoDefault(False)
        self.launch_button_tab1.setDefault(False)
        self.launch_button_tab1.setFlat(False)
        self.launch_button_tab1.setObjectName("launch_button_tab1")
        self.verticalLayout_input_layout.addWidget(self.launch_button_tab1)
        self.verticalLayout_input_layout.setStretch(0, 1)
        self.verticalLayout_input_layout.setStretch(1, 3)
        self.verticalLayout_input_layout.setStretch(2, 1)
        self.verticalLayout_input_layout.setStretch(3, 1)
        self.horizontalLayout_main.addLayout(self.verticalLayout_input_layout)
        self.line = QtWidgets.QFrame(self.tab1)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_main.addWidget(self.line)
        self.layout_graphics_tab1 = QtWidgets.QVBoxLayout()
        self.layout_graphics_tab1.setContentsMargins(10, -1, 16, 5)
        self.layout_graphics_tab1.setObjectName("layout_graphics_tab1")
        self.horizontalLayout_main.addLayout(self.layout_graphics_tab1)
        self.horizontalLayout_main.setStretch(0, 1)
        self.horizontalLayout_main.setStretch(2, 4)
        self.horizontalLayout_tab.addLayout(self.horizontalLayout_main)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_tab)
        self.tabWidget.addTab(self.tab1, "")
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setEnabled(True)
        self.tab2.setObjectName("tab2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.tab2)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_tab_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_tab_2.setSpacing(0)
        self.horizontalLayout_tab_2.setObjectName("horizontalLayout_tab_2")
        self.horizontalLayout_main_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_main_2.setSpacing(0)
        self.horizontalLayout_main_2.setObjectName("horizontalLayout_main_2")
        self.verticalLayout_input_layout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_input_layout_2.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_input_layout_2.setObjectName("verticalLayout_input_layout_2")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_input_layout_2.addItem(spacerItem3)
        self.layout_parameters_tab2 = QtWidgets.QVBoxLayout()
        self.layout_parameters_tab2.setSpacing(8)
        self.layout_parameters_tab2.setObjectName("layout_parameters_tab2")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.layout_parameters_tab2.addItem(spacerItem4)
        self.label_parameters_2 = QtWidgets.QLabel(self.tab2)
        self.label_parameters_2.setObjectName("label_parameters_2")
        self.layout_parameters_tab2.addWidget(self.label_parameters_2)
        self.verticalLayout_input_layout_2.addLayout(self.layout_parameters_tab2)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_input_layout_2.addItem(spacerItem5)
        self.launch_button_tab2 = QtWidgets.QPushButton(self.tab2)
        self.launch_button_tab2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.launch_button_tab2.sizePolicy().hasHeightForWidth())
        self.launch_button_tab2.setSizePolicy(sizePolicy)
        self.launch_button_tab2.setMinimumSize(QtCore.QSize(0, 30))
        self.launch_button_tab2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.launch_button_tab2.setStyleSheet("#pushButton {\n"
"  border: 1px solid#adadad;\n"
"  background-color: rgb(225, 225, 225);\n"
"  color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"#pushButton:hover {\n"
"  border: 1px solid#0078d7;\n"
"  background-color: rgb(229, 241, 251);\n"
"  color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"#pushButton:pressed {  \n"
"  border: 1px solid#005499;\n"
"  background-color: rgb(204, 228, 247);\n"
"  color: rgb(0, 0, 0);\n"
"}")
        self.launch_button_tab2.setCheckable(False)
        self.launch_button_tab2.setChecked(False)
        self.launch_button_tab2.setAutoRepeat(False)
        self.launch_button_tab2.setAutoExclusive(False)
        self.launch_button_tab2.setAutoDefault(False)
        self.launch_button_tab2.setDefault(False)
        self.launch_button_tab2.setFlat(False)
        self.launch_button_tab2.setObjectName("launch_button_tab2")
        self.verticalLayout_input_layout_2.addWidget(self.launch_button_tab2)
        self.verticalLayout_input_layout_2.setStretch(0, 1)
        self.verticalLayout_input_layout_2.setStretch(1, 3)
        self.verticalLayout_input_layout_2.setStretch(2, 1)
        self.verticalLayout_input_layout_2.setStretch(3, 1)
        self.horizontalLayout_main_2.addLayout(self.verticalLayout_input_layout_2)
        self.line_2 = QtWidgets.QFrame(self.tab2)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_main_2.addWidget(self.line_2)
        self.layout_graphics_tab2 = QtWidgets.QVBoxLayout()
        self.layout_graphics_tab2.setContentsMargins(10, -1, 16, 5)
        self.layout_graphics_tab2.setObjectName("layout_graphics_tab2")
        self.horizontalLayout_main_2.addLayout(self.layout_graphics_tab2)
        self.horizontalLayout_main_2.setStretch(0, 1)
        self.horizontalLayout_main_2.setStretch(2, 4)
        self.horizontalLayout_tab_2.addLayout(self.horizontalLayout_main_2)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_tab_2)
        self.tabWidget.addTab(self.tab2, "")
        self.tab3 = QtWidgets.QWidget()
        self.tab3.setObjectName("tab3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.tab3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_tab_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_tab_4.setSpacing(0)
        self.horizontalLayout_tab_4.setObjectName("horizontalLayout_tab_4")
        self.horizontalLayout_main_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_main_4.setSpacing(0)
        self.horizontalLayout_main_4.setObjectName("horizontalLayout_main_4")
        self.verticalLayout_input_layout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_input_layout_4.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_input_layout_4.setObjectName("verticalLayout_input_layout_4")
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_input_layout_4.addItem(spacerItem6)
        self.layout_parameters_tab3 = QtWidgets.QVBoxLayout()
        self.layout_parameters_tab3.setSpacing(8)
        self.layout_parameters_tab3.setObjectName("layout_parameters_tab3")
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.layout_parameters_tab3.addItem(spacerItem7)
        self.label_parameters_4 = QtWidgets.QLabel(self.tab3)
        self.label_parameters_4.setObjectName("label_parameters_4")
        self.layout_parameters_tab3.addWidget(self.label_parameters_4)
        self.verticalLayout_input_layout_4.addLayout(self.layout_parameters_tab3)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_input_layout_4.addItem(spacerItem8)
        self.launch_button_tab3 = QtWidgets.QPushButton(self.tab3)
        self.launch_button_tab3.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.launch_button_tab3.sizePolicy().hasHeightForWidth())
        self.launch_button_tab3.setSizePolicy(sizePolicy)
        self.launch_button_tab3.setMinimumSize(QtCore.QSize(0, 30))
        self.launch_button_tab3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.launch_button_tab3.setStyleSheet("#pushButton {\n"
"  border: 1px solid#adadad;\n"
"  background-color: rgb(225, 225, 225);\n"
"  color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"#pushButton:hover {\n"
"  border: 1px solid#0078d7;\n"
"  background-color: rgb(229, 241, 251);\n"
"  color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"#pushButton:pressed {  \n"
"  border: 1px solid#005499;\n"
"  background-color: rgb(204, 228, 247);\n"
"  color: rgb(0, 0, 0);\n"
"}")
        self.launch_button_tab3.setCheckable(False)
        self.launch_button_tab3.setChecked(False)
        self.launch_button_tab3.setAutoRepeat(False)
        self.launch_button_tab3.setAutoExclusive(False)
        self.launch_button_tab3.setAutoDefault(False)
        self.launch_button_tab3.setDefault(False)
        self.launch_button_tab3.setFlat(False)
        self.launch_button_tab3.setObjectName("launch_button_tab3")
        self.verticalLayout_input_layout_4.addWidget(self.launch_button_tab3)
        self.verticalLayout_input_layout_4.setStretch(0, 1)
        self.verticalLayout_input_layout_4.setStretch(1, 3)
        self.verticalLayout_input_layout_4.setStretch(2, 1)
        self.verticalLayout_input_layout_4.setStretch(3, 1)
        self.horizontalLayout_main_4.addLayout(self.verticalLayout_input_layout_4)
        self.line_4 = QtWidgets.QFrame(self.tab3)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_main_4.addWidget(self.line_4)
        self.layout_graphics_tab3 = QtWidgets.QVBoxLayout()
        self.layout_graphics_tab3.setContentsMargins(10, -1, 16, 5)
        self.layout_graphics_tab3.setObjectName("layout_graphics_tab3")
        self.horizontalLayout_main_4.addLayout(self.layout_graphics_tab3)
        self.horizontalLayout_main_4.setStretch(0, 1)
        self.horizontalLayout_main_4.setStretch(2, 4)
        self.horizontalLayout_tab_4.addLayout(self.horizontalLayout_main_4)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_tab_4)
        self.tabWidget.addTab(self.tab3, "")
        self.horizontalLayout_2.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_parameters.setText(_translate("MainWindow", "Параметры:"))
        self.launch_button_tab1.setText(_translate("MainWindow", "Запуск"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("MainWindow", "Надёжный прибор"))
        self.label_parameters_2.setText(_translate("MainWindow", "Параметры:"))
        self.launch_button_tab2.setText(_translate("MainWindow", "Запуск"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("MainWindow", "Ненадёжный прибор"))
        self.label_parameters_4.setText(_translate("MainWindow", "Параметры:"))
        self.launch_button_tab3.setText(_translate("MainWindow", "Запуск"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab3), _translate("MainWindow", "Ненадёжный прибор2"))
