# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'data/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(427, 359)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: \"white\";\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_input_layout = QtWidgets.QVBoxLayout()
        self.verticalLayout_input_layout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_input_layout.setObjectName("verticalLayout_input_layout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_input_layout.addItem(spacerItem)
        self.verticalLayout_parameters = QtWidgets.QVBoxLayout()
        self.verticalLayout_parameters.setSpacing(8)
        self.verticalLayout_parameters.setObjectName("verticalLayout_parameters")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_parameters.addItem(spacerItem1)
        self.label_parameters = QtWidgets.QLabel(self.centralwidget)
        self.label_parameters.setObjectName("label_parameters")
        self.verticalLayout_parameters.addWidget(self.label_parameters)
        self.verticalLayout_input_layout.addLayout(self.verticalLayout_parameters)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_input_layout.addItem(spacerItem2)
        self.lunch_button = QtWidgets.QPushButton(self.centralwidget)
        self.lunch_button.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lunch_button.sizePolicy().hasHeightForWidth())
        self.lunch_button.setSizePolicy(sizePolicy)
        self.lunch_button.setMinimumSize(QtCore.QSize(0, 30))
        self.lunch_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lunch_button.setStyleSheet("#pushButton {\n"
"  border: 1px solid#adadad;\n"
"  background-color: rgb(225, 225, 225);\n"
"  color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"#pushButton:hover {\n"
"  border: 1px solid#0078d7;\n"
"  background-color: rgb(229, 241, 251);\n"
"  color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"#pushButton:pressed {  \n"
"  border: 1px solid#005499;\n"
"  background-color: rgb(204, 228, 247);\n"
"  color: rgb(0, 0, 0);\n"
"}")
        self.lunch_button.setCheckable(False)
        self.lunch_button.setChecked(False)
        self.lunch_button.setAutoRepeat(False)
        self.lunch_button.setAutoExclusive(False)
        self.lunch_button.setAutoDefault(False)
        self.lunch_button.setDefault(False)
        self.lunch_button.setFlat(False)
        self.lunch_button.setObjectName("lunch_button")
        self.verticalLayout_input_layout.addWidget(self.lunch_button)
        self.verticalLayout_input_layout.setStretch(0, 1)
        self.verticalLayout_input_layout.setStretch(1, 3)
        self.verticalLayout_input_layout.setStretch(2, 1)
        self.verticalLayout_input_layout.setStretch(3, 1)
        self.horizontalLayout.addLayout(self.verticalLayout_input_layout)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.verticalLayout_graphic_widgets = QtWidgets.QVBoxLayout()
        self.verticalLayout_graphic_widgets.setContentsMargins(10, -1, 16, 5)
        self.verticalLayout_graphic_widgets.setObjectName("verticalLayout_graphic_widgets")
        self.horizontalLayout.addLayout(self.verticalLayout_graphic_widgets)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(2, 4)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_parameters.setText(_translate("MainWindow", "Параметры:"))
        self.lunch_button.setText(_translate("MainWindow", "Запуск"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
