# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'data\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(680, 400)
        MainWindow.setMinimumSize(QtCore.QSize(680, 400))
        MainWindow.setStyleSheet("QMainWindow {background-color: \"white\"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_centralwidget = QtWidgets.QHBoxLayout()
        self.horizontalLayout_centralwidget.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_centralwidget.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_centralwidget.setSpacing(0)
        self.horizontalLayout_centralwidget.setObjectName("horizontalLayout_centralwidget")
        self.frame_launch_panel = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_launch_panel.sizePolicy().hasHeightForWidth())
        self.frame_launch_panel.setSizePolicy(sizePolicy)
        self.frame_launch_panel.setStyleSheet("QFrame {\n"
"background-color: \"white\";\n"
"}")
        self.frame_launch_panel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_launch_panel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_launch_panel.setLineWidth(0)
        self.frame_launch_panel.setObjectName("frame_launch_panel")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_launch_panel)
        self.verticalLayout.setContentsMargins(10, 10, 0, 10)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_main_panel = QtWidgets.QVBoxLayout()
        self.verticalLayout_main_panel.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_main_panel.setSpacing(0)
        self.verticalLayout_main_panel.setObjectName("verticalLayout_main_panel")
        spacerItem = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_main_panel.addItem(spacerItem)
        self.verticalLayout_input_panel = QtWidgets.QVBoxLayout()
        self.verticalLayout_input_panel.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_input_panel.setSpacing(8)
        self.verticalLayout_input_panel.setObjectName("verticalLayout_input_panel")
        spacerItem1 = QtWidgets.QSpacerItem(133, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_input_panel.addItem(spacerItem1)
        self.label_parameters = QtWidgets.QLabel(self.frame_launch_panel)
        self.label_parameters.setObjectName("label_parameters")
        self.verticalLayout_input_panel.addWidget(self.label_parameters)
        self.verticalLayout_parameters = QtWidgets.QVBoxLayout()
        self.verticalLayout_parameters.setSpacing(8)
        self.verticalLayout_parameters.setObjectName("verticalLayout_parameters")
        self.verticalLayout_input_panel.addLayout(self.verticalLayout_parameters)
        self.verticalLayout_main_panel.addLayout(self.verticalLayout_input_panel)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_main_panel.addItem(spacerItem2)
        self.lunch_button = QtWidgets.QPushButton(self.frame_launch_panel)
        self.lunch_button.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lunch_button.sizePolicy().hasHeightForWidth())
        self.lunch_button.setSizePolicy(sizePolicy)
        self.lunch_button.setMinimumSize(QtCore.QSize(0, 30))
        self.lunch_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lunch_button.setStyleSheet("#pushButton {\n"
"  border: 1px solid#adadad;\n"
"  background-color: rgb(225, 225, 225);\n"
"  color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"#pushButton:hover {\n"
"  border: 1px solid#0078d7;\n"
"  background-color: rgb(229, 241, 251);\n"
"  color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"#pushButton:pressed {  \n"
"  border: 1px solid#005499;\n"
"  background-color: rgb(204, 228, 247);\n"
"  color: rgb(0, 0, 0);\n"
"}")
        self.lunch_button.setCheckable(False)
        self.lunch_button.setChecked(False)
        self.lunch_button.setAutoRepeat(False)
        self.lunch_button.setAutoExclusive(False)
        self.lunch_button.setAutoDefault(False)
        self.lunch_button.setDefault(False)
        self.lunch_button.setFlat(False)
        self.lunch_button.setObjectName("lunch_button")
        self.verticalLayout_main_panel.addWidget(self.lunch_button)
        self.verticalLayout.addLayout(self.verticalLayout_main_panel)
        self.horizontalLayout_centralwidget.addWidget(self.frame_launch_panel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout.setContentsMargins(10, 10, 6, 10)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.horizontalLayout_centralwidget.addLayout(self.horizontalLayout)
        self.verticalLayout_graphic_widgets = QtWidgets.QVBoxLayout()
        self.verticalLayout_graphic_widgets.setContentsMargins(10, -1, 10, 5)
        self.verticalLayout_graphic_widgets.setSpacing(0)
        self.verticalLayout_graphic_widgets.setObjectName("verticalLayout_graphic_widgets")
        spacerItem3 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_graphic_widgets.addItem(spacerItem3)
        self.horizontalLayout_centralwidget.addLayout(self.verticalLayout_graphic_widgets)
        self.verticalLayout_2.addLayout(self.horizontalLayout_centralwidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_parameters.setText(_translate("MainWindow", "Параметры:"))
        self.lunch_button.setText(_translate("MainWindow", "Запуск"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
